<script lang="ts" setup>
import { computed, onMounted, ref } from 'vue';
import { Card as ACard, Col as ACol, Descriptions as ADescriptions, DescriptionsItem as ADescriptionsItem, Empty as AEmpty, Row as ARow, Select as ASelect, Space as ASpace, Spin as ASpin, Tag as ATag, message } from 'ant-design-vue';

type Center = { id: string; name: string; code: string };
type Node = { id: string; enabled: boolean; name: string };
type Server = { id: string; listenPort: number };
type Upstream = { id: string };
type NodeMetric = { nodeId:string; nodeName:string; host:string; port:number; available:boolean; message?:string; activeConnections?:number; accepts?:number; handled?:number; requests?:number; reading?:number; writing?:number; waiting?:number };
const centers=ref<Center[]>([]),centerId=ref<string>(),nodes=ref<Node[]>([]),servers=ref<Server[]>([]),upstreams=ref<Upstream[]>([]),streamServers=ref<Server[]>([]),nodeMetrics=ref<NodeMetric[]>([]),loading=ref(false),metricsLoading=ref(false);
async function request<T>(path:string):Promise<T>{const response=await fetch(`/api${path}`);if(!response.ok)throw new Error('请求失败');return response.json();}
async function loadNodeMetrics(){if(!centerId.value)return;metricsLoading.value=true;try{nodeMetrics.value=await request<NodeMetric[]>(`/centers/${centerId.value}/node-metrics`)}catch{nodeMetrics.value=[];message.warning('节点运行指标读取失败')}finally{metricsLoading.value=false}}
async function load(id:string){centerId.value=id;loading.value=true;try{const [a,b,c,d]=await Promise.all([request<Node[]>(`/centers/${id}/nodes`),request<Server[]>(`/centers/${id}/http/servers`),request<Upstream[]>(`/centers/${id}/http/upstreams`),request<Server[]>(`/centers/${id}/stream/servers`)]);nodes.value=a;servers.value=b;upstreams.value=c;streamServers.value=d;await loadNodeMetrics()}catch(error){message.error(error instanceof Error?error.message:'加载 Dashboard 失败')}finally{loading.value=false}}
const metrics=computed(()=>[{label:'节点实例',value:nodes.value.length,suffix:'台',tone:'blue'},{label:'启用节点',value:nodes.value.filter(x=>x.enabled).length,suffix:'台',tone:'green'},{label:'HTTP Server',value:servers.value.length,suffix:'个',tone:'violet'},{label:'HTTP Upstream',value:upstreams.value.length,suffix:'组',tone:'cyan'},{label:'Stream Server',value:streamServers.value.length,suffix:'个',tone:'orange'},{label:'监听端口',value:new Set([...servers.value,...streamServers.value].map(x=>x.listenPort)).size,suffix:'个',tone:'slate'}]);
const httpPorts=computed(()=>servers.value.map(x=>x.listenPort).join('、')||'暂无'),streamPorts=computed(()=>streamServers.value.map(x=>x.listenPort).join('、')||'暂无');
onMounted(async()=>{try{centers.value=await request<Center[]>('/centers');if(centers.value[0])await load(centers.value[0].id)}catch(e){message.error(e instanceof Error?e.message:'加载配置中心失败')}});
</script>
<template><div class="ops-page dashboard-page"><a-card :bordered="false" class="dashboard-hero"><div class="dashboard-hero__content"><div><div class="dashboard-hero__title">运行 Dashboard</div><div class="dashboard-hero__description">集中查看所选配置中心的实例、监听端口和运行指标。</div></div><a-space class="dashboard-hero__selector" wrap><span>配置中心</span><a-select v-model:value="centerId" :loading="loading" class="dashboard-center-select" :options="centers.map(x=>({value:x.id,label:`${x.name}（${x.code}）`}))" @change="load"/></a-space></div></a-card><a-row class="dashboard-metrics" :gutter="[16,16]"><a-col v-for="x in metrics" :key="x.label" :xs="24" :sm="12" :lg="8" :xl="4"><a-card :bordered="false" class="metric-card" :class="`metric-card--${x.tone}`" :loading="loading"><div class="metric-card__label">{{x.label}}</div><div class="metric-card__value">{{x.value}}<span>{{x.suffix}}</span></div></a-card></a-col></a-row><a-card :bordered="false" title="节点运行指标" :loading="metricsLoading"><template #extra><a-tag color="blue">每次进入中心时刷新</a-tag></template><a-empty v-if="!nodeMetrics.length" description="暂无可读取的 HTTP 节点指标"/><a-row v-else :gutter="[16,16]"><a-col v-for="node in nodeMetrics" :key="node.nodeId" :xs="24" :xl="12"><div class="node-metric-card"><div class="node-metric-card__head"><div><b>{{node.nodeName}}</b><span>{{node.host}}:{{node.port}}</span></div><a-tag :color="node.available?'green':'default'">{{node.available?'运行中':'无法读取'}}</a-tag></div><div v-if="node.available" class="node-metric-grid"><div><span>活动连接</span><strong>{{node.activeConnections}}</strong></div><div><span>总连接次数</span><strong>{{node.accepts}}</strong></div><div><span>总握手次数</span><strong>{{node.handled}}</strong></div><div><span>总请求数</span><strong>{{node.requests}}</strong></div><div><span>请求数 Reading</span><strong>{{node.reading}}</strong></div><div><span>响应数 Writing</span><strong>{{node.writing}}</strong></div><div><span>驻留进程 Waiting</span><strong>{{node.waiting}}</strong></div></div><div v-else class="node-metric-unavailable">{{node.message}}</div></div></a-col></a-row></a-card><a-card :bordered="false" title="配置摘要" :loading="loading"><a-descriptions bordered :column="{xs:1,sm:2}"><a-descriptions-item label="HTTP 监听端口">{{httpPorts}}</a-descriptions-item><a-descriptions-item label="Stream 监听端口">{{streamPorts}}</a-descriptions-item><a-descriptions-item label="节点实例"><a-space wrap><a-tag v-for="node in nodes" :key="node.id" color="blue">{{node.name}}</a-tag></a-space></a-descriptions-item><a-descriptions-item label="配置数据源">MySQL 配置中心</a-descriptions-item></a-descriptions></a-card></div></template>
<style scoped>.dashboard-page{display:grid;gap:16px}.dashboard-hero__content{display:flex;min-height:84px;align-items:center;justify-content:space-between;gap:24px}.dashboard-hero__title{font-size:20px;font-weight:600}.dashboard-hero__description,.metric-card__label,.node-metric-card__head span,.node-metric-grid span,.node-metric-unavailable{color:var(--ant-color-text-secondary);font-size:13px}.dashboard-hero__selector{align-items:center}.dashboard-center-select{width:260px}.dashboard-metrics{margin:0!important}.metric-card{min-height:122px;border-left:3px solid var(--ant-color-primary)}.metric-card__value{margin-top:12px;font-size:30px;font-weight:600}.metric-card__value span{margin-left:5px;font-size:14px;font-weight:400}.node-metric-card{border:1px solid var(--ant-color-border-secondary);border-radius:10px;padding:16px}.node-metric-card__head{display:flex;align-items:flex-start;justify-content:space-between;margin-bottom:16px}.node-metric-card__head span{display:block;margin-top:4px}.node-metric-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.node-metric-grid div{padding:10px;border-radius:7px;background:var(--ant-color-fill-quaternary)}.node-metric-grid span,.node-metric-grid strong{display:block}.node-metric-grid strong{font-size:22px;margin-top:4px}.node-metric-unavailable{padding:24px 0}@media(max-width:768px){.dashboard-hero__content{align-items:flex-start;flex-direction:column}.dashboard-center-select{width:min(100%,300px)}.node-metric-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}</style>
