<script lang="ts" setup>
import { computed, onMounted, onUnmounted, ref } from 'vue';
import { Alert as AAlert, Card as ACard, Form as AForm, FormItem as AFormItem, Select as ASelect, Tabs as ATabs, TabPane as ATabPane, Tag as ATag, message } from 'ant-design-vue';

type Center = { id: string; name: string; code: string };
type Node = { id: string; name: string; host: string; servicePort: number; enabled: boolean };
type Server = { domain?: string; serviceName?: string; listenPort: number; accessLog: string; errorLog: string };
type LogEvent = { type?: string; path: string; message: string; timestamp?: string; receivedAt: number; nodeName?: string };
const centers = ref<Center[]>([]), nodes = ref<Node[]>([]), servers = ref<Server[]>([]), centerId = ref<string>(), nodeId = ref<string>(), path = ref(''), lines = ref<string[]>([]), activeType = ref<'access'|'error'>('access'), loading = ref(false), connected = ref(false), lastUpdated = ref<Date>();
let eventSource: EventSource | undefined;
async function request<T>(url: string): Promise<T> { const response = await fetch(`/api${url}`); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.detail || body.message || '请求失败'); } return response.json() as Promise<T>; }
const nodeOptions = computed(() => nodes.value.map(item => ({ value: item.id, label: `${item.name}（${item.host}:${item.servicePort}）` })));
const logOptions = computed(() => { const values = new Set<string>(); servers.value.forEach(item => { const value = activeType.value === 'access' ? item.accessLog : item.errorLog; if (value) values.add(value); }); return [...values].map(value => ({ value, label: value })); });
const centerLabel = computed(() => { const value = centers.value.find(item => item.id === centerId.value); return value ? `${value.name}（${value.code}）` : '请选择中心'; });
async function loadCenter(id: string) { centerId.value = id; nodeId.value = undefined; servers.value = []; lines.value = []; const [nodeList, httpServers, streamServers] = await Promise.all([request<Node[]>(`/centers/${id}/nodes`), request<Server[]>(`/centers/${id}/http/servers`), request<Server[]>(`/centers/${id}/stream/servers`)]); nodes.value = nodeList; servers.value = [...httpServers, ...streamServers]; nodeId.value = nodeList.find(item => item.enabled)?.id || nodeList[0]?.id; path.value = logOptions.value[0]?.value || ''; await refresh(); }
function connect() { eventSource?.close(); connected.value = false; lines.value = []; if (!nodeId.value) return; eventSource = new EventSource(`/api/centers/${centerId.value}/nodes/${nodeId.value}/logs/stream`); eventSource.addEventListener('ready', () => { connected.value = true; loading.value = false; }); eventSource.addEventListener('log', (event) => { const item = JSON.parse((event as MessageEvent).data) as LogEvent; if (path.value && item.path && item.path !== path.value) return; if (item.type && item.type !== activeType.value) return; lines.value = [...lines.value, `${item.timestamp || new Date(item.receivedAt).toISOString()} ${item.message}`].slice(-300); lastUpdated.value = new Date(); }); eventSource.onerror = () => { connected.value = false; loading.value = false; }; }
function refresh() { connect(); }
function switchType(value: string) { activeType.value = value as 'access'|'error'; path.value = logOptions.value[0]?.value || ''; connect(); }
onMounted(async () => { try { centers.value = await request<Center[]>('/centers'); if (centers.value[0]) await loadCenter(centers.value[0].id); } catch (error) { message.error(error instanceof Error ? error.message : '加载日志页面失败'); } });
onUnmounted(() => { eventSource?.close(); });
</script>
<template><div class="ops-page"><a-card :bordered="false" title="OpenResty 实例日志"><a-form layout="inline"><a-form-item label="配置中心"><a-select v-model:value="centerId" class="w-72" :options="centers.map(item => ({ value: item.id, label: `${item.name}（${item.code}）` }))" @change="loadCenter" /></a-form-item><a-form-item label="OpenResty 实例"><a-select v-model:value="nodeId" class="w-96" :options="nodeOptions" @change="refresh" /></a-form-item><a-form-item label="日志文件"><a-select v-model:value="path" class="w-96" :options="logOptions" allow-clear show-search @change="refresh" /></a-form-item></a-form><div class="mt-3 flex items-center gap-2"><a-tag color="blue">{{ centerLabel }}</a-tag><a-tag :color="connected ? 'green' : 'orange'">{{ connected ? 'Kafka 实时连接' : '等待 Kafka 日志' }}</a-tag><span class="text-gray-500">{{ lastUpdated ? `最近更新：${lastUpdated.toLocaleTimeString()}` : '等待读取' }}</span></div></a-card><a-tabs class="mt-4" :active-key="activeType" @change="switchType"><a-tab-pane key="access" tab="访问日志"/><a-tab-pane key="error" tab="错误日志"/></a-tabs><a-card :bordered="false" :loading="loading"><a-alert v-if="!path" type="info" show-icon message="当前中心没有可读取的日志文件配置。请先为 HTTP Server 或 Stream Server 配置访问日志、错误日志路径。"/><pre v-else class="log-console">{{ lines.length ? lines.join('\n') : '等待 Kafka 推送日志…' }}</pre></a-card></div></template>
<style scoped>.log-console{max-height:620px;overflow:auto;margin:0;padding:16px;border-radius:8px;background:#111827;color:#d1fae5;font:12px/1.65 ui-monospace,SFMono-Regular,Menlo,monospace;white-space:pre-wrap;word-break:break-word}</style>
