# Nginx 1.31.5 is the first OSS release with the official Control REST API.
# The Lua modules are compiled in; no OpenResty/Nginx source is patched.
FROM alpine:3.22 AS build

ARG NGINX_VERSION=1.31.5
ARG LUA_NGINX_MODULE_VERSION=v0.10.31rc5
ARG STREAM_LUA_MODULE_VERSION=v0.0.19rc4
ARG LUA_RESTY_CORE_VERSION=v0.1.34rc2
ARG LUA_RESTY_LRUCACHE_VERSION=v0.10
ARG LUA_CJSON_VERSION=2.1.0.19
ARG NDK_VERSION=v0.3.4
ARG LUAJIT_VERSION=v2.1-20250826

RUN apk add --no-cache build-base curl linux-headers openssl-dev pcre2-dev perl zlib-dev

WORKDIR /build
RUN curl -fsSLO "https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz" \
 && curl -fsSLO "https://github.com/vision5/ngx_devel_kit/archive/refs/tags/${NDK_VERSION}.tar.gz" \
 && curl -fsSLO "https://github.com/openresty/lua-nginx-module/archive/refs/tags/${LUA_NGINX_MODULE_VERSION}.tar.gz" \
 && curl -fsSLO "https://github.com/openresty/stream-lua-nginx-module/archive/refs/tags/${STREAM_LUA_MODULE_VERSION}.tar.gz" \
 && curl -fsSLO "https://github.com/openresty/lua-resty-core/archive/refs/tags/${LUA_RESTY_CORE_VERSION}.tar.gz" \
 && curl -fsSLO "https://github.com/openresty/lua-resty-lrucache/archive/refs/tags/${LUA_RESTY_LRUCACHE_VERSION}.tar.gz" \
 && curl -fsSLO "https://github.com/openresty/lua-cjson/archive/refs/tags/${LUA_CJSON_VERSION}.tar.gz" \
 && curl -fsSLO "https://github.com/openresty/luajit2/archive/refs/tags/${LUAJIT_VERSION}.tar.gz" \
 && tar -xzf "nginx-${NGINX_VERSION}.tar.gz" \
 && tar -xzf "${NDK_VERSION}.tar.gz" \
 && tar -xzf "${LUA_NGINX_MODULE_VERSION}.tar.gz" \
 && tar -xzf "${STREAM_LUA_MODULE_VERSION}.tar.gz" \
 && tar -xzf "${LUA_RESTY_CORE_VERSION}.tar.gz" \
 && tar -xzf "${LUA_RESTY_LRUCACHE_VERSION}.tar.gz" \
 && tar -xzf "${LUA_CJSON_VERSION}.tar.gz" \
 && tar -xzf "${LUAJIT_VERSION}.tar.gz"

WORKDIR /build/luajit2-${LUAJIT_VERSION#v}
RUN make -j"$(getconf _NPROCESSORS_ONLN)" \
 && make install PREFIX=/usr/local/openresty/luajit

WORKDIR /build/lua-cjson-${LUA_CJSON_VERSION}
RUN make LUA_INCLUDE_DIR=/usr/local/openresty/luajit/include/luajit-2.1 \
 && install -Dm755 cjson.so /usr/local/openresty/lualib/cjson.so

WORKDIR /build/nginx-${NGINX_VERSION}
ENV LUAJIT_LIB=/usr/local/openresty/luajit/lib
ENV LUAJIT_INC=/usr/local/openresty/luajit/include/luajit-2.1
RUN ./configure \
      --prefix=/usr/local/openresty/nginx \
      --sbin-path=/usr/local/openresty/nginx/sbin/openresty \
      --conf-path=/usr/local/openresty/nginx/conf/nginx.conf \
      --pid-path=/var/run/openresty.pid \
      --error-log-path=/dev/stderr \
      --http-log-path=/dev/stdout \
      --with-control-api \
      --with-http_ssl_module \
      --with-http_v2_module \
      --with-http_realip_module \
      --with-http_stub_status_module \
      --with-stream \
      --with-stream_ssl_module \
      --with-stream_ssl_preread_module \
      --with-threads \
      --with-pcre-jit \
      --add-module=/build/ngx_devel_kit-${NDK_VERSION#v} \
      --add-module=/build/lua-nginx-module-${LUA_NGINX_MODULE_VERSION#v} \
      --add-module=/build/stream-lua-nginx-module-${STREAM_LUA_MODULE_VERSION#v} \
 && make -j"$(getconf _NPROCESSORS_ONLN)" \
 && make install

FROM alpine:3.22
RUN apk add --no-cache curl socat libgcc libstdc++ openssl pcre2 zlib \
 && addgroup -S nginx \
 && adduser -S -D -H -G nginx nginx \
 && install -d -o nginx -g nginx /run/openresty /etc/openresty/conf.d /etc/openresty/lua /var/log/nginx
COPY --from=build /usr/local/openresty /usr/local/openresty
COPY --from=build /build/lua-resty-core-0.1.34rc2/lib /usr/local/openresty/lualib
COPY --from=build /build/lua-resty-lrucache-0.10/lib /usr/local/openresty/lualib
COPY nginx.conf /usr/local/openresty/nginx/conf/nginx.conf
COPY conf.d /etc/openresty/conf.d
COPY lua /etc/openresty/lua
COPY entrypoint.sh /usr/local/bin/openresty-entrypoint
RUN chmod 755 /usr/local/bin/openresty-entrypoint
ENV LD_LIBRARY_PATH=/usr/local/openresty/luajit/lib
EXPOSE 80 81
ENTRYPOINT ["/usr/local/bin/openresty-entrypoint"]
CMD ["-g", "daemon off;", "-l", "unix:/run/openresty/control.sock"]
