<script lang="ts" setup>
import { computed, onMounted, ref } from 'vue';
import { Button as AButton, Card as ACard, Drawer as ADrawer, Form as AForm, FormItem as AFormItem, Input as AInput, InputNumber as AInputNumber, Select as ASelect, Switch as ASwitch, Table as ATable, Tag as ATag, message } from 'ant-design-vue';

type Center = { id: string; code: string; name: string; enabled: boolean };
type Node = { id: string; name: string; protocol: 'HTTP' | 'STREAM_TCP' | 'STREAM_UDP'; host: string; servicePort: number; controlApiUrl?: string; enabled: boolean };
type Upstream = { id: string; name: string; keepaliveConnections: number };
const centers = ref<Center[]>([]); const nodes = ref<Node[]>([]); const upstreams = ref<Upstream[]>([]);
const selectedCenterId = ref<string>(); const loading = ref(false);
const centerOpen = ref(false); const nodeOpen = ref(false); const upstreamOpen = ref(false);
const editingCenterId = ref<string>(); const editingNodeId = ref<string>(); const editingUpstreamId = ref<string>();
const newCenter = () => ({ code: '', name: '', enabled: true });
const newNode = () => ({ name: '', protocol: 'HTTP' as Node['protocol'], host: '', servicePort: 80, controlApiUrl: '', enabled: true });
const newUpstream = () => ({ name: '', keepaliveConnections: 32 });
const centerForm = ref(newCenter()); const nodeForm = ref(newNode()); const upstreamForm = ref(newUpstream());
const selectedCenter = computed(() => centers.value.find((item) => item.id === selectedCenterId.value));
const protocolLabel = (value: Node['protocol']) => ({ HTTP: 'HTTP（七层）', STREAM_TCP: 'TCP（四层）', STREAM_UDP: 'UDP（四层）' })[value];
const centerColumns = [{ dataIndex: 'code', key: 'code', title: '中心标识' }, { dataIndex: 'name', key: 'name', title: '中心名称' }, { dataIndex: 'enabled', key: 'enabled', title: '状态' }, { key: 'action', title: '操作', width: 210 }];
const nodeColumns = [{ dataIndex: 'name', key: 'name', title: '实例名称' }, { dataIndex: 'protocol', key: 'protocol', title: '协议' }, { dataIndex: 'host', key: 'host', title: '域名 / IP' }, { dataIndex: 'servicePort', key: 'servicePort', title: '端口' }, { dataIndex: 'controlApiUrl', key: 'controlApiUrl', title: 'Control API' }, { dataIndex: 'enabled', key: 'enabled', title: '状态' }, { key: 'action', title: '操作', width: 130 }];
const upstreamColumns = [{ dataIndex: 'name', key: 'name', title: '服务标识' }, { dataIndex: 'keepaliveConnections', key: 'keepaliveConnections', title: 'Keepalive 连接数' }, { key: 'action', title: '操作', width: 130 }];
async function request<T>(path: string, options?: RequestInit): Promise<T> { const response = await fetch(`/api${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(options?.headers ?? {}) } }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.detail || body.message || '请求失败'); } return response.status === 204 ? (undefined as T) : response.json() as Promise<T>; }
async function loadCenters() { loading.value = true; try { centers.value = await request<Center[]>('/centers'); if (!selectedCenterId.value && centers.value[0]) await selectCenter(centers.value[0].id); } catch (error) { message.error(error instanceof Error ? error.message : '加载中心失败'); } finally { loading.value = false; } }
async function selectCenter(centerId: string) { selectedCenterId.value = centerId; try { [nodes.value, upstreams.value] = await Promise.all([request<Node[]>(`/centers/${centerId}/nodes`), request<Upstream[]>(`/centers/${centerId}/http/upstreams`)]); } catch (error) { message.error(error instanceof Error ? error.message : '加载中心配置失败'); } }
function openCenter(value?: Center) { editingCenterId.value = value?.id; centerForm.value = value ? { code: value.code, name: value.name, enabled: value.enabled } : newCenter(); centerOpen.value = true; }
function openNode(value?: Node) { editingNodeId.value = value?.id; nodeForm.value = value ? { name: value.name, protocol: value.protocol, host: value.host, servicePort: value.servicePort, controlApiUrl: value.controlApiUrl || '', enabled: value.enabled } : newNode(); nodeOpen.value = true; }
function openUpstream(value?: Upstream) { editingUpstreamId.value = value?.id; upstreamForm.value = value ? { name: value.name, keepaliveConnections: value.keepaliveConnections } : newUpstream(); upstreamOpen.value = true; }
async function saveCenter() { try { const item = editingCenterId.value ? await request<Center>(`/centers/${editingCenterId.value}`, { method: 'PUT', body: JSON.stringify(centerForm.value) }) : await request<Center>('/centers', { method: 'POST', body: JSON.stringify(centerForm.value) }); centerOpen.value = false; await loadCenters(); await selectCenter(item.id); message.success(editingCenterId.value ? '中心已更新' : '中心已创建'); } catch (error) { message.error(error instanceof Error ? error.message : '保存中心失败'); } }
async function saveNode() { if (!selectedCenterId.value) return; try { await request<Node>(`/centers/${selectedCenterId.value}/nodes${editingNodeId.value ? `/${editingNodeId.value}` : ''}`, { method: editingNodeId.value ? 'PUT' : 'POST', body: JSON.stringify(nodeForm.value) }); nodeOpen.value = false; await selectCenter(selectedCenterId.value); message.success(editingNodeId.value ? '节点已更新' : '节点已创建'); } catch (error) { message.error(error instanceof Error ? error.message : '保存节点失败'); } }
async function saveUpstream() { if (!selectedCenterId.value) return; try { await request<Upstream>(`/centers/${selectedCenterId.value}/http/upstreams${editingUpstreamId.value ? `/${editingUpstreamId.value}` : ''}`, { method: editingUpstreamId.value ? 'PUT' : 'POST', body: JSON.stringify(upstreamForm.value) }); upstreamOpen.value = false; await selectCenter(selectedCenterId.value); message.success(editingUpstreamId.value ? 'Upstream 已更新' : 'Upstream 已创建'); } catch (error) { message.error(error instanceof Error ? error.message : '保存 Upstream 失败'); } }
async function remove(path: string, title: string) { try { await request(path, { method: 'DELETE' }); await loadCenters(); if (selectedCenterId.value && centers.value.some(item => item.id === selectedCenterId.value)) await selectCenter(selectedCenterId.value); else { selectedCenterId.value = undefined; nodes.value = []; upstreams.value = []; } message.success(`${title}已删除`); } catch (error) { message.error(error instanceof Error ? error.message : `删除${title}失败`); } }
onMounted(loadCenters);
</script>
<template><div class="p-5">
  <a-card :bordered="false" title="中心与 OpenResty 节点"><template #extra><a-button type="primary" @click="openCenter()">新增中心</a-button></template><a-table :columns="centerColumns" :data-source="centers" :loading="loading" :pagination="false" row-key="id"><template #bodyCell="{ column, record }"><template v-if="column.key === 'enabled'"><a-tag :color="record.enabled ? 'green' : 'default'">{{ record.enabled ? '已启用' : '已停用' }}</a-tag></template><template v-else-if="column.key === 'action'"><a-button type="link" @click="selectCenter(record.id)">查看</a-button><a-button type="link" @click="openCenter(record)">编辑</a-button><a-popconfirm title="确认删除该中心及其配置？" @confirm="remove(`/centers/${record.id}`, '中心')"><a-button danger type="link">删除</a-button></a-popconfirm></template></template></a-table></a-card>
  <a-card class="mt-5" :bordered="false" :title="selectedCenter ? `${selectedCenter.name} 的节点实例` : '请选择中心'"><template #extra><a-button type="primary" :disabled="!selectedCenterId" @click="openNode()">新增节点</a-button></template><a-table :columns="nodeColumns" :data-source="nodes" :pagination="false" row-key="id"><template #bodyCell="{ column, record }"><template v-if="column.key === 'protocol'">{{ protocolLabel(record.protocol) }}</template><template v-else-if="column.key === 'enabled'"><a-tag :color="record.enabled ? 'green' : 'default'">{{ record.enabled ? '已启用' : '已停用' }}</a-tag></template><template v-else-if="column.key === 'controlApiUrl'">{{ record.controlApiUrl || '未配置' }}</template><template v-else-if="column.key === 'action'"><a-button type="link" @click="openNode(record)">编辑</a-button><a-popconfirm title="确认删除该节点？" @confirm="remove(`/centers/${selectedCenterId}/nodes/${record.id}`, '节点')"><a-button danger type="link">删除</a-button></a-popconfirm></template></template></a-table></a-card>
  <a-card class="mt-5" :bordered="false" :title="selectedCenter ? `${selectedCenter.name} 的 HTTP Upstream` : '请选择中心'"><template #extra><a-button type="primary" :disabled="!selectedCenterId" @click="openUpstream()">新增 Upstream</a-button></template><a-table :columns="upstreamColumns" :data-source="upstreams" :pagination="false" row-key="id"><template #bodyCell="{ column, record }"><template v-if="column.key === 'action'"><a-button type="link" @click="openUpstream(record)">编辑</a-button><a-popconfirm title="确认删除该 Upstream？" @confirm="remove(`/centers/${selectedCenterId}/http/upstreams/${record.id}`, 'Upstream')"><a-button danger type="link">删除</a-button></a-popconfirm></template></template></a-table></a-card>
  <a-drawer v-model:open="centerOpen" :title="editingCenterId ? '编辑中心' : '新增中心'" :width="480" @close="centerOpen = false"><a-form layout="vertical"><a-form-item label="中心标识" required><a-input v-model:value="centerForm.code" placeholder="如 east" /></a-form-item><a-form-item label="中心名称" required><a-input v-model:value="centerForm.name" placeholder="如 华东中心" /></a-form-item><a-form-item label="启用状态"><a-switch v-model:checked="centerForm.enabled" checked-children="启用" un-checked-children="停用" /></a-form-item></a-form><template #footer><div class="flex justify-end gap-2"><a-button @click="centerOpen=false">取消</a-button><a-button type="primary" @click="saveCenter">保存</a-button></div></template></a-drawer>
  <a-drawer v-model:open="nodeOpen" :title="editingNodeId ? '编辑 OpenResty 节点' : '新增 OpenResty 节点'" :width="520" @close="nodeOpen=false"><a-form layout="vertical"><a-form-item label="实例名称" required><a-input v-model:value="nodeForm.name" /></a-form-item><a-form-item label="协议" required><a-select v-model:value="nodeForm.protocol" :options="[{ value: 'HTTP', label: '七层 HTTP（HTTP）' }, { value: 'STREAM_TCP', label: '四层 TCP（STREAM_TCP）' }, { value: 'STREAM_UDP', label: '四层 UDP（STREAM_UDP）' }]" /></a-form-item><a-form-item label="域名 / IP" required><a-input v-model:value="nodeForm.host" /></a-form-item><a-form-item label="服务端口" required><a-input-number v-model:value="nodeForm.servicePort" :max="65535" :min="1" class="w-full" /></a-form-item><a-form-item label="Control API 地址"><a-input v-model:value="nodeForm.controlApiUrl" placeholder="如 http://node-control:9000" /></a-form-item><a-form-item label="启用状态"><a-switch v-model:checked="nodeForm.enabled" checked-children="启用" un-checked-children="停用" /></a-form-item></a-form><template #footer><div class="flex justify-end gap-2"><a-button @click="nodeOpen=false">取消</a-button><a-button type="primary" @click="saveNode">保存</a-button></div></template></a-drawer>
  <a-drawer v-model:open="upstreamOpen" :title="editingUpstreamId ? '编辑 HTTP Upstream' : '新增 HTTP Upstream'" :width="480" @close="upstreamOpen=false"><a-form layout="vertical"><a-form-item label="服务标识" required><a-input v-model:value="upstreamForm.name" placeholder="如 order" /></a-form-item><a-form-item label="Keepalive 连接数" required><a-input-number v-model:value="upstreamForm.keepaliveConnections" :min="1" :max="10000" class="w-full" /></a-form-item></a-form><template #footer><div class="flex justify-end gap-2"><a-button @click="upstreamOpen=false">取消</a-button><a-button type="primary" @click="saveUpstream">保存</a-button></div></template></a-drawer>
</div></template>
