<script lang="ts" setup>
import { computed, h, onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';
import { Alert as AAlert, Button as AButton, Card as ACard, Col as ACol, Drawer as ADrawer, Empty as AEmpty, Form as AForm, FormItem as AFormItem, Input as AInput, InputNumber as AInputNumber, Popconfirm as APopconfirm, Progress as AProgress, Row as ARow, Select as ASelect, Space as ASpace, Switch as ASwitch, Table as ATable, Tabs as ATabs, TabPane as ATabPane, Tag as ATag, Timeline as ATimeline, TimelineItem as ATimelineItem, Tooltip as ATooltip, message } from 'ant-design-vue';
import { type PageResult, useServerPagination } from '#/utils/server-pagination';

type Center={id:string;code:string;name:string;enabled:boolean};
type Node={id:string;name:string;host:string;servicePort:number;controlApiUrl?:string;enabled:boolean};
type Target={id:string;targetHost:string;targetPort:number;enabled:boolean};
type HttpUpstream={id:string;name:string;keepaliveConnections:number;healthCheckEnabled:boolean;targets:Target[]};
type HttpServer={id:string;domain:string;listenPort:number;sslEnabled:boolean};
type Location={id:string;path:string};
type StreamUpstream={id:string;name:string;targetHost:string;targetPort:number};
type StreamServer={id:string;serviceName:string;listenPort:number;protocol:'TCP'|'UDP'};
type Audit={id:string;actor:string;action:string;result:string;createdAt:string};
type Version={versionNo:number;createdAt:string}; type Reload={status:string;createdAt:string}; type Health={status:string};

const centers=ref<Center[]>([]),centerRows=ref<Center[]>([]),nodes=ref<Node[]>([]),nodeRows=ref<Node[]>([]),httpUpstreams=ref<HttpUpstream[]>([]),httpServers=ref<HttpServer[]>([]),locations=ref<(Location&{serverId:string})[]>([]),streamUpstreams=ref<StreamUpstream[]>([]),streamServers=ref<StreamServer[]>([]),audits=ref<Audit[]>([]),versions=ref<Version[]>([]),reloads=ref<Reload[]>([]);
const centerPager=useServerPagination(),nodePager=useServerPagination();
const selectedCenterId=ref<string>(),loading=ref(false),healthLoading=ref(false),activeTab=ref('operations');
const centerOpen=ref(false),nodeOpen=ref(false),editingCenterId=ref<string>(),editingNodeId=ref<string>();
const healthStates=ref<Record<string,'HEALTHY'|'UNHEALTHY'|'UNKNOWN'>>({});
const router = useRouter();
const freshCenter=()=>({code:'',name:'',enabled:true}),freshNode=()=>({name:'',host:'',servicePort:80,controlApiUrl:'',enabled:true});
const centerForm=ref(freshCenter()),nodeForm=ref(freshNode());
const selectedCenter=computed(()=>centers.value.find(v=>v.id===selectedCenterId.value));
const enabledNodes=computed(()=>nodes.value.filter(v=>v.enabled).length);
const listenPorts=computed(()=>[...new Set([...nodes.value.map(v=>v.servicePort),...httpServers.value.map(v=>v.listenPort),...streamServers.value.map(v=>v.listenPort)])].sort((a,b)=>a-b));
const targetCount=computed(()=>httpUpstreams.value.reduce((n,v)=>n+v.targets.filter(t=>t.enabled).length,0)+streamUpstreams.value.length);
const healthy=computed(()=>httpUpstreams.value.filter(v=>healthStates.value[v.id]==='HEALTHY').length),unhealthy=computed(()=>httpUpstreams.value.filter(v=>healthStates.value[v.id]==='UNHEALTHY').length);
const metrics=computed(()=>[
 {label:'节点实例',value:nodes.value.length,suffix:'台',hint:`${enabledNodes.value} 台已启用`,tone:enabledNodes.value===nodes.value.length?'green':'orange'},
 {label:'监听端口',value:listenPorts.value.length,suffix:'个',hint:listenPorts.value.join('、')||'尚未配置',tone:'blue'},
 {label:'HTTP Server',value:httpServers.value.length,suffix:'个',hint:`${new Set(httpServers.value.map(v=>v.domain)).size} 个域名`,tone:'cyan'},
 {label:'Location / API',value:locations.value.length,suffix:'个',hint:'七层路由配置',tone:'purple'},
 {label:'全部 Upstream',value:httpUpstreams.value.length+streamUpstreams.value.length,suffix:'组',hint:`${targetCount.value} 个有效后端`,tone:'green'},
 {label:'Stream 服务',value:streamServers.value.length,suffix:'个',hint:`${streamUpstreams.value.length} 个四层 Upstream`,tone:'orange'},
 {label:'运行版本',value:versions.value[0]?`v${versions.value[0].versionNo}`:'未发布',hint:formatTime(versions.value[0]?.createdAt),tone:'blue'},
 {label:'最近重载',value:reloadLabel(reloads.value[0]?.status),hint:formatTime(reloads.value[0]?.createdAt),tone:reloads.value[0]?.status==='SUCCESS'?'green':'orange'},
]);
const configData=computed(()=>[{name:'HTTP Server',value:httpServers.value.length},{name:'Location',value:locations.value.length},{name:'HTTP Upstream',value:httpUpstreams.value.length},{name:'Stream Server',value:streamServers.value.length},{name:'Stream Upstream',value:streamUpstreams.value.length}]);
const healthPercent=computed(()=>httpUpstreams.value.length?Math.round(healthy.value/httpUpstreams.value.length*100):0);
const centerColumns=[{dataIndex:'code',key:'code',title:'中心标识'},{dataIndex:'name',key:'name',title:'中心名称'},{key:'enabled',title:'状态',width:100},{key:'action',title:'操作',width:210}];
const headerHelp=(label:string,tip:string)=>h(ATooltip,{title:tip},{default:()=>h('span',{},[label,h('span',{class:'table-header-help'},' ?')])});const nodeColumns=[{dataIndex:'name',key:'name',title:'实例名称'},{key:'endpoint',title:headerHelp('访问端点','用于访问节点上的 HTTP/OpenResty 业务端点，例如读取状态和健康信息。')},{key:'controlApiUrl',title:headerHelp('Control API','用于管理节点，例如执行配置 reload；它与业务访问端口可以不同。')},{key:'enabled',title:'状态',width:100},{key:'action',title:'操作',width:130}];

async function request<T>(path:string,options?:RequestInit):Promise<T>{const r=await fetch(`/api${path}`,{...options,headers:{'Content-Type':'application/json',...(options?.headers??{})}});if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.detail||b.message||'请求失败')}return r.status===204?undefined as T:r.json()}
function formatTime(v?:string){return v?new Date(v).toLocaleString('zh-CN',{hour12:false}):'—'}
function reloadLabel(v?:string){return ({SUCCESS:'成功',FAILED:'失败',PARTIAL_SUCCESS:'部分成功',RUNNING:'执行中'} as Record<string,string>)[v||'']||'无记录'}
function auditLabel(v:string){return ({CENTER_CREATED:'创建中心',CENTER_UPDATED:'更新中心',NGINX_NODE_CREATED:'创建节点',NGINX_NODE_UPDATED:'更新节点',HTTP_SERVER_CREATED:'创建 HTTP Server',HTTP_LOCATION_CREATED:'创建 Location',HTTP_UPSTREAM_CREATED:'创建 HTTP Upstream',STREAM_SERVER_CREATED:'创建 Stream Server',RUNTIME_CONFIGURATION_PUBLISHED:'发布运行版本',CONTROL_API_RELOAD:'执行配置重载'} as Record<string,string>)[v]||v}
async function loadCenterPage(){centerRows.value=centerPager.apply(await request<PageResult<Center>>(`/centers/paged?${centerPager.query()}`))}
async function loadNodePage(){if(!selectedCenterId.value)return;nodeRows.value=nodePager.apply(await request<PageResult<Node>>(`/centers/${selectedCenterId.value}/nodes/paged?${nodePager.query()}`))}
async function changeCenterPage(p:any){centerPager.change(p);await loadCenterPage()}
async function changeNodePage(p:any){nodePager.change(p);await loadNodePage()}
async function loadCenters(){loading.value=true;try{centers.value=await request('/centers');await loadCenterPage();if(!selectedCenterId.value&&centers.value[0])await selectCenter(centers.value[0].id)}catch(e){message.error(e instanceof Error?e.message:'加载中心失败')}finally{loading.value=false}}
async function selectCenter(id:string){selectedCenterId.value=id;nodePager.reset();loading.value=true;healthStates.value={};try{const [n,hu,hs,su,ss,a,v,r]=await Promise.all([request<Node[]>(`/centers/${id}/nodes`),request<HttpUpstream[]>(`/centers/${id}/http/upstreams`),request<HttpServer[]>(`/centers/${id}/http/servers`),request<StreamUpstream[]>(`/centers/${id}/stream/upstreams`),request<StreamServer[]>(`/centers/${id}/stream/servers`),request<Audit[]>(`/centers/${id}/audit-events`).catch(()=>[]),request<Version[]>(`/centers/${id}/runtime-configurations`).catch(()=>[]),request<Reload[]>(`/centers/${id}/control-api-reloads`).catch(()=>[])]);nodes.value=n;await loadNodePage();httpUpstreams.value=hu;httpServers.value=hs;streamUpstreams.value=su;streamServers.value=ss;audits.value=a.slice(0,6);versions.value=v;reloads.value=r;locations.value=(await Promise.all(hs.map(s=>request<Location[]>(`/centers/${id}/http/servers/${s.id}/locations`).then(items=>items.map(x=>({...x,serverId:s.id})))))).flat();hu.forEach(u=>healthStates.value[u.id]=u.targets.some(t=>t.enabled)?'UNKNOWN':'UNHEALTHY')}catch(e){message.error(e instanceof Error?e.message:'加载中心运维数据失败')}finally{loading.value=false}}
async function refreshHealth(){if(!selectedCenterId.value)return;healthLoading.value=true;try{healthStates.value=Object.fromEntries(await Promise.all(httpUpstreams.value.map(async u=>{if(!u.healthCheckEnabled)return [u.id,u.targets.some(t=>t.enabled)?'UNKNOWN':'UNHEALTHY'];const values=await request<Health[]>(`/centers/${selectedCenterId.value}/http/upstreams/${u.id}/health-checks`).catch(()=>[]);return [u.id,values.length&&values.every(v=>v.status==='HEALTHY')?'HEALTHY':'UNHEALTHY']})));message.success('Upstream 状态已刷新')}finally{healthLoading.value=false}}
function openCenter(v?:Center){editingCenterId.value=v?.id;centerForm.value=v?{code:v.code,name:v.name,enabled:v.enabled}:freshCenter();centerOpen.value=true}
function openNode(v?:Node){editingNodeId.value=v?.id;nodeForm.value=v?{name:v.name,host:v.host,servicePort:v.servicePort,controlApiUrl:v.controlApiUrl||'',enabled:v.enabled}:freshNode();nodeOpen.value=true}
function openNodeHttpConfig(node:Node){if(!selectedCenterId.value)return;router.push({path:'/openresty/http-config',query:{centerId:selectedCenterId.value,nodeId:node.id}})}
function openNodeStreamConfig(node:Node){if(!selectedCenterId.value)return;router.push({path:'/openresty/stream-config',query:{centerId:selectedCenterId.value,nodeId:node.id}})}
async function saveCenter(){try{const item=editingCenterId.value?await request<Center>(`/centers/${editingCenterId.value}`,{method:'PUT',body:JSON.stringify(centerForm.value)}):await request<Center>('/centers',{method:'POST',body:JSON.stringify(centerForm.value)});centerOpen.value=false;await loadCenters();await selectCenter(item.id);message.success(editingCenterId.value?'中心已更新':'中心已创建')}catch(e){message.error(e instanceof Error?e.message:'保存中心失败')}}
async function saveNode(){if(!selectedCenterId.value)return;try{await request(`/centers/${selectedCenterId.value}/nodes${editingNodeId.value?`/${editingNodeId.value}`:''}`,{method:editingNodeId.value?'PUT':'POST',body:JSON.stringify(nodeForm.value)});nodeOpen.value=false;await selectCenter(selectedCenterId.value);message.success(editingNodeId.value?'节点已更新':'节点已创建')}catch(e){message.error(e instanceof Error?e.message:'保存节点失败')}}
async function remove(path:string,title:string){try{await request(path,{method:'DELETE'});await loadCenters();if(selectedCenterId.value&&centers.value.some(v=>v.id===selectedCenterId.value))await selectCenter(selectedCenterId.value);message.success(`${title}已删除`)}catch(e){message.error(e instanceof Error?e.message:`删除${title}失败`)}}
onMounted(loadCenters);
</script>

<template><div class="ops-page">
 <a-card :bordered="false"><div class="ops-toolbar"><div><div class="text-xl font-semibold">中心与节点管理</div><div class="mt-2 text-sm text-gray-500">维护配置中心及其关联的 OpenResty 实例。</div></div><a-space wrap><a-select v-model:value="selectedCenterId" class="w-72" :options="centers.map(v=>({value:v.id,label:`${v.name}（${v.code}）`}))" placeholder="选择中心" @change="selectCenter"/><a-button :loading="loading" @click="selectedCenterId&&selectCenter(selectedCenterId)">刷新数据</a-button><a-button type="primary" @click="openCenter()">新增中心</a-button></a-space></div></a-card>
 <a-alert v-if="selectedCenter&&(!nodes.length||!httpServers.length&&!streamServers.length)" type="warning" show-icon message="当前中心仍有运行配置缺口" :description="!nodes.length?'尚未关联 OpenResty 节点，配置无法下发到实例。':'尚未配置任何 HTTP 或 Stream 监听服务。'"/>
 <a-card :bordered="false"><a-tabs v-model:active-key="activeTab">
  <a-tab-pane key="operations" tab="实例与监听"><div class="ops-toolbar mb-4"><div><div class="text-base font-medium">{{selectedCenter?.name||'请选择中心'}} 的节点实例</div><div class="mt-1 text-sm text-gray-500">监听端口：{{listenPorts.join('、')||'未配置'}}</div></div><a-button type="primary" :disabled="!selectedCenterId" @click="openNode()">新增节点</a-button></div><a-table :columns="nodeColumns" :data-source="nodeRows" :loading="loading" :pagination="nodePager.table.value" row-key="id" @change="changeNodePage"><template #emptyText><a-empty description="当前中心还没有节点实例"/></template><template #bodyCell="{column,record}"><template v-if="column.key==='endpoint'"><span class="font-mono">{{record.host}}:{{record.servicePort}}</span></template><template v-else-if="column.key==='controlApiUrl'">{{record.controlApiUrl||'未配置'}}</template><template v-else-if="column.key==='enabled'"><a-tag :color="record.enabled?'green':'default'">{{record.enabled?'运行中':'已停用'}}</a-tag></template><template v-else-if="column.key==='action'"><a-button type="link" @click="openNodeHttpConfig(record)">配置 HTTP</a-button><a-button type="link" @click="openNodeStreamConfig(record)">配置 Stream</a-button><a-button type="link" @click="openNode(record)">编辑实例</a-button><a-popconfirm title="确认删除该节点？" @confirm="remove(`/centers/${selectedCenterId}/nodes/${record.id}`,'节点')"><a-button danger type="link">删除</a-button></a-popconfirm></template></template></a-table></a-tab-pane>
  <a-tab-pane key="centers" tab="中心管理"><div class="mb-4 flex justify-end"><a-button type="primary" @click="openCenter()">新增中心</a-button></div><a-table :columns="centerColumns" :data-source="centerRows" :pagination="centerPager.table.value" row-key="id" @change="changeCenterPage"><template #bodyCell="{column,record}"><template v-if="column.key==='enabled'"><a-tag :color="record.enabled?'green':'default'">{{record.enabled?'已启用':'已停用'}}</a-tag></template><template v-else-if="column.key==='action'"><a-button type="link" @click="selectCenter(record.id);activeTab='operations'">查看</a-button><a-button type="link" @click="openCenter(record)">编辑</a-button><a-popconfirm title="确认删除该中心及其配置？" @confirm="remove(`/centers/${record.id}`,'中心')"><a-button danger type="link">删除</a-button></a-popconfirm></template></template></a-table></a-tab-pane>
 </a-tabs></a-card>
 <a-drawer v-model:open="centerOpen" :title="editingCenterId?'编辑中心':'新增中心'" :width="520"><a-form layout="vertical"><a-form-item label="中心标识" required><a-input v-model:value="centerForm.code" placeholder="如 east"/></a-form-item><a-form-item label="中心名称" required><a-input v-model:value="centerForm.name" placeholder="如 华东中心"/></a-form-item><a-form-item label="启用状态"><a-switch v-model:checked="centerForm.enabled" checked-children="启用" un-checked-children="停用"/></a-form-item></a-form><template #footer><div class="flex justify-end gap-2"><a-button @click="centerOpen=false">取消</a-button><a-button type="primary" @click="saveCenter">保存</a-button></div></template></a-drawer>
 <a-drawer v-model:open="nodeOpen" :title="editingNodeId?'编辑 OpenResty 节点':'新增 OpenResty 节点'" :width="560"><a-form layout="vertical"><a-form-item label="实例名称" required><a-input v-model:value="nodeForm.name"/></a-form-item><a-row :gutter="16"><a-col :span="16"><a-form-item label="域名 / IP" required><a-input v-model:value="nodeForm.host"/></a-form-item></a-col><a-col :span="8"><a-form-item label="服务端口" required><a-input-number v-model:value="nodeForm.servicePort" :max="65535" :min="1" class="w-full"/></a-form-item></a-col></a-row><a-form-item label="Control API 地址"><a-input v-model:value="nodeForm.controlApiUrl" placeholder="如 http://node-control:9000"/></a-form-item><a-form-item label="启用状态"><a-switch v-model:checked="nodeForm.enabled" checked-children="启用" un-checked-children="停用"/></a-form-item></a-form><template #footer><div class="flex justify-end gap-2"><a-button @click="nodeOpen=false">取消</a-button><a-button type="primary" @click="saveNode">保存</a-button></div></template></a-drawer>
</div></template>
<style scoped>
.table-header-help { color: var(--ant-color-primary); cursor: help; font-weight: 700; }
</style>
