<script lang="ts" setup>
import { onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';
import { Button as AButton, Card as ACard, Checkbox as ACheckbox, Drawer as ADrawer, Form as AForm, FormItem as AFormItem, Input as AInput, Select as ASelect, Space as ASpace, Table as ATable, Tabs as ATabs, TabPane as ATabPane, Tag as ATag } from 'ant-design-vue';
import { type PageResult, useServerPagination } from '#/utils/server-pagination';
type Center={id:string;name:string;code:string}; type Server={id:string;domain:string;listenPort:number;sslEnabled:boolean;rootPath?:string;responseHeaders:string[]};
const router=useRouter(), centers=ref<Center[]>([]), rows=ref<Server[]>([]), centerId=ref<string>(), drawer=ref(false), editing=ref<Server>(), section=ref('basic');
const pager=useServerPagination(); const securityHeaders=['X-Frame-Options: SAMEORIGIN','X-Content-Type-Options: nosniff','Strict-Transport-Security: max-age=31536000; includeSubDomains',"Content-Security-Policy: default-src 'self'",'Referrer-Policy: strict-origin-when-cross-origin'];
const columns=[{dataIndex:'domain',title:'域名'},{dataIndex:'listenPort',title:'端口'},{key:'tls',title:'TLS'},{key:'action',title:'操作'}];
async function api<T>(path:string):Promise<T>{return (await fetch(`/api${path}`)).json()}; async function load(){if(centerId.value)rows.value=pager.apply(await api<PageResult<Server>>(`/centers/${centerId.value}/http/servers/paged?${pager.query()}`))}; function open(value:Server){editing.value={...value,responseHeaders:[...(value.responseHeaders||[])]};drawer.value=true}; function goLocations(){if(editing.value)router.push({path:'/openresty/http-locations',query:{centerId:centerId.value,serverId:editing.value.id}})}; function toggleHeader(header:string,enabled:boolean){if(!editing.value)return;editing.value.responseHeaders=enabled?[...new Set([...editing.value.responseHeaders,header])]:editing.value.responseHeaders.filter(value=>value!==header)}; onMounted(async()=>{centers.value=await api<Center[]>('/centers');centerId.value=centers.value[0]?.id;await load()});
</script>
<template><div class="ops-page"><a-card :bordered="false" title="HTTP Server 配置"><a-form layout="inline"><a-form-item label="中心"><a-select v-model:value="centerId" class="w-72" :options="centers.map(v=>({value:v.id,label:`${v.name}（${v.code}）`}))" @change="load"/></a-form-item></a-form></a-card><a-card class="mt-4" :bordered="false"><a-table :columns="columns" :data-source="rows" :pagination="pager.table.value" row-key="id" @change="(p:any)=>{pager.change(p);load()}"><template #bodyCell="{column,record}"><template v-if="column.key==='tls'"><a-tag :color="record.sslEnabled?'green':'default'">{{record.sslEnabled?'已启用':'未启用'}}</a-tag></template><template v-else-if="column.key==='action'"><a-button type="link" @click="open(record)">详情与编辑</a-button></template></template></a-table></a-card><a-drawer v-model:open="drawer" :title="`${editing?.domain||''}:${editing?.listenPort||''} · Server 配置`" :width="760"><a-tabs v-model:active-key="section" tab-position="left"><a-tab-pane key="basic" tab="基本"><a-form layout="vertical"><a-form-item label="网站目录"><a-input v-model:value="editing!.rootPath"/></a-form-item></a-form></a-tab-pane><a-tab-pane key="location" tab="Location 配置"><a-button type="primary" @click="goLocations">进入 Location 配置</a-button></a-tab-pane><a-tab-pane key="security" tab="安全配置"><a-space direction="vertical" fill><a-checkbox v-for="header in securityHeaders" :key="header" :checked="editing?.responseHeaders.includes(header)" @change="(event:any)=>toggleHeader(header,event.target.checked)">{{header}}</a-checkbox></a-space></a-tab-pane><a-tab-pane key="headers" tab="响应头"><a-form layout="vertical"><a-form-item label="自定义响应头"><a-select v-model:value="editing!.responseHeaders" mode="tags" :token-separators="[',']" placeholder="Header-Name: value"/></a-form-item></a-form></a-tab-pane><a-tab-pane key="tls" tab="HTTPS">TLS 证书与协议配置</a-tab-pane><a-tab-pane key="other" tab="其他">访问策略、限速与重定向</a-tab-pane></a-tabs></a-drawer></div></template>
