package net.daoke.openrestyplus.httpconfig;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import net.daoke.openrestyplus.audit.AuditService;
import net.daoke.openrestyplus.center.CenterRepository;
import net.daoke.openrestyplus.health.HealthCheckType;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;
import java.util.*;

@RestController
@RequestMapping("/api/centers/{centerId}/http/upstreams")
public class HttpUpstreamController {
  private final CenterRepository centers; private final HttpUpstreamRepository upstreams; private final HttpUpstreamTargetRepository targets; private final HttpUpstreamHealthCheckService healthChecks; private final AuditService audit;
  public HttpUpstreamController(CenterRepository centers,HttpUpstreamRepository upstreams,HttpUpstreamTargetRepository targets,HttpUpstreamHealthCheckService healthChecks,AuditService audit){this.centers=centers;this.upstreams=upstreams;this.targets=targets;this.healthChecks=healthChecks;this.audit=audit;}
  @GetMapping public List<View> list(@PathVariable UUID centerId){requireCenter(centerId);return upstreams.findByCenterIdOrderByName(centerId).stream().map(this::view).toList();}
  @GetMapping("/paged") public net.daoke.openrestyplus.web.PageResult<View> paged(@PathVariable UUID centerId,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="10") int size){return net.daoke.openrestyplus.web.PageResult.of(list(centerId),page,size);}
  @GetMapping("/{upstreamId}/targets/paged") public net.daoke.openrestyplus.web.PageResult<TargetView> pagedTargets(@PathVariable UUID centerId,@PathVariable UUID upstreamId,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="10") int size){requireUpstream(centerId,upstreamId);return net.daoke.openrestyplus.web.PageResult.of(targets.findByUpstreamIdOrderByTargetHostAscTargetPortAsc(upstreamId).stream().map(TargetView::from).toList(),page,size);}
  @PostMapping @ResponseStatus(HttpStatus.CREATED) public View create(@PathVariable UUID centerId,@Valid @RequestBody Create request){requireCenter(centerId);var saved=upstreams.save(new HttpUpstream(centerId,request.name(),request.keepaliveConnections(),request.zoneSizeKilobytes(),request.healthCheckEnabled(),request.healthCheckType(),request.healthCheckPath(),request.healthCheckIntervalSeconds(),request.healthCheckTimeoutMilliseconds(),request.healthCheckExpectedStatus(),request.healthCheckHost(),request.healthCheckRequestHeaders(),request.healthCheckRise(),request.healthCheckFall()));audit.success(centerId,"HTTP_UPSTREAM_CREATED","HTTP_UPSTREAM",saved.getId());return view(saved);}
  @PutMapping("/{upstreamId}") public View update(@PathVariable UUID centerId,@PathVariable UUID upstreamId,@Valid @RequestBody Create request){var upstream=requireUpstream(centerId,upstreamId);upstream.apply(request.name(),request.keepaliveConnections(),request.zoneSizeKilobytes(),request.healthCheckEnabled(),request.healthCheckType(),request.healthCheckPath(),request.healthCheckIntervalSeconds(),request.healthCheckTimeoutMilliseconds(),request.healthCheckExpectedStatus(),request.healthCheckHost(),request.healthCheckRequestHeaders(),request.healthCheckRise(),request.healthCheckFall());var saved=upstreams.save(upstream);audit.success(centerId,"HTTP_UPSTREAM_UPDATED","HTTP_UPSTREAM",upstreamId);return view(saved);}
  @DeleteMapping("/{upstreamId}") @ResponseStatus(HttpStatus.NO_CONTENT) public void delete(@PathVariable UUID centerId,@PathVariable UUID upstreamId){upstreams.delete(requireUpstream(centerId,upstreamId));audit.success(centerId,"HTTP_UPSTREAM_DELETED","HTTP_UPSTREAM",upstreamId);}
  @GetMapping("/{upstreamId}/health-checks") public List<HttpUpstreamHealthCheckService.Result> healthChecks(@PathVariable UUID centerId,@PathVariable UUID upstreamId){var upstream=requireUpstream(centerId,upstreamId);return healthChecks.check(upstream,targets.findByUpstreamIdOrderByTargetHostAscTargetPortAsc(upstreamId));}
  @PostMapping("/{upstreamId}/targets") @ResponseStatus(HttpStatus.CREATED) public TargetView createTarget(@PathVariable UUID centerId,@PathVariable UUID upstreamId,@Valid @RequestBody TargetRequest request){requireUpstream(centerId,upstreamId);var value=targets.save(new HttpUpstreamTarget(upstreamId,request.targetHost(),request.targetPort(),request.weight(),request.maxFails(),request.failTimeoutSeconds(),request.resolveEnabled(),request.backup(),request.enabled()));audit.success(centerId,"HTTP_UPSTREAM_TARGET_CREATED","HTTP_UPSTREAM_TARGET",value.getId());return TargetView.from(value);}
  @PutMapping("/{upstreamId}/targets/{targetId}") public TargetView updateTarget(@PathVariable UUID centerId,@PathVariable UUID upstreamId,@PathVariable UUID targetId,@Valid @RequestBody TargetRequest request){requireUpstream(centerId,upstreamId);var value=requireTarget(upstreamId,targetId);value.apply(request.targetHost(),request.targetPort(),request.weight(),request.maxFails(),request.failTimeoutSeconds(),request.resolveEnabled(),request.backup(),request.enabled());targets.save(value);audit.success(centerId,"HTTP_UPSTREAM_TARGET_UPDATED","HTTP_UPSTREAM_TARGET",targetId);return TargetView.from(value);}
  @DeleteMapping("/{upstreamId}/targets/{targetId}") @ResponseStatus(HttpStatus.NO_CONTENT) public void deleteTarget(@PathVariable UUID centerId,@PathVariable UUID upstreamId,@PathVariable UUID targetId){requireUpstream(centerId,upstreamId);targets.delete(requireTarget(upstreamId,targetId));audit.success(centerId,"HTTP_UPSTREAM_TARGET_DELETED","HTTP_UPSTREAM_TARGET",targetId);}
  private void requireCenter(UUID id){if(!centers.existsById(id))throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Center not found");}
  private HttpUpstream requireUpstream(UUID centerId,UUID id){requireCenter(centerId);return upstreams.findById(id).filter(v->upstreams.existsByIdAndCenterId(v.getId(),centerId)).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"HTTP upstream not found"));}
  private HttpUpstreamTarget requireTarget(UUID upstreamId,UUID id){return targets.findById(id).filter(v->v.getUpstreamId().equals(upstreamId)).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"HTTP upstream target not found"));}
  private View view(HttpUpstream value){return new View(value.getId(),value.getName(),value.getKeepaliveConnections(),value.getZoneSizeKilobytes(),value.isHealthCheckEnabled(),value.getHealthCheckType(),value.getHealthCheckPath(),value.getHealthCheckIntervalSeconds(),value.getHealthCheckTimeoutMilliseconds(),value.getHealthCheckExpectedStatus(),value.getHealthCheckHost(),value.getHealthCheckRequestHeaders(),value.getHealthCheckRise(),value.getHealthCheckFall(),targets.findByUpstreamIdOrderByTargetHostAscTargetPortAsc(value.getId()).stream().map(TargetView::from).toList());}
  public record Create(@NotBlank String name,@Min(1) @Max(10000) int keepaliveConnections,@Min(8) @Max(65536) int zoneSizeKilobytes,boolean healthCheckEnabled,@NotNull HealthCheckType healthCheckType,@NotBlank @Pattern(regexp="/[0-9A-Za-z._~!$&'()*+,;=:@%/-]{0,254}") String healthCheckPath,@Min(1) @Max(3600) int healthCheckIntervalSeconds,@Min(50) @Max(60000) int healthCheckTimeoutMilliseconds,@Min(100) @Max(599) int healthCheckExpectedStatus,@Pattern(regexp="[0-9A-Za-z.-]{0,253}") String healthCheckHost,@NotNull List<@Pattern(regexp="[^\\r\\n]{1,512}") String> healthCheckRequestHeaders,@Min(1)@Max(100) int healthCheckRise,@Min(1)@Max(100) int healthCheckFall){}
  public record TargetRequest(@NotBlank @Pattern(regexp="[0-9A-Za-z:.\\-]{1,253}") String targetHost,@Min(1) @Max(65535) int targetPort,@Min(1) @Max(1000) int weight,@Min(0) @Max(100) int maxFails,@Min(1) @Max(3600) int failTimeoutSeconds,boolean resolveEnabled,boolean backup,boolean enabled){}
  public record TargetView(UUID id,String targetHost,int targetPort,int weight,int maxFails,int failTimeoutSeconds,boolean resolveEnabled,boolean backup,boolean enabled){static TargetView from(HttpUpstreamTarget v){return new TargetView(v.getId(),v.getTargetHost(),v.getTargetPort(),v.getWeight(),v.getMaxFails(),v.getFailTimeoutSeconds(),v.isResolveEnabled(),v.isBackup(),v.isEnabled());}}
  public record View(UUID id,String name,int keepaliveConnections,int zoneSizeKilobytes,boolean healthCheckEnabled,HealthCheckType healthCheckType,String healthCheckPath,int healthCheckIntervalSeconds,int healthCheckTimeoutMilliseconds,int healthCheckExpectedStatus,String healthCheckHost,List<String> healthCheckRequestHeaders,int healthCheckRise,int healthCheckFall,List<TargetView> targets){}
}
